import { useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/navbar';
import Footer from '../components/footer';

const menuItems = [
  {
    id: 1,
    name: 'Latte',
    description: 'Espresso shots with steamed milk and a layer of foam',
    price: '$3.50',
  },
  {
    id: 2,
    name: 'Cappuccino',
    description: 'Espresso shots with equal parts steamed milk and foam',
    price: '$3.00',
  },
  {
    id: 3,
    name: 'Americano',
    description: 'Espresso shots with hot water',
    price: '$2.50',
  },
];

const Menu: NextPage = () => {
  const [newMenuItem, setNewMenuItem] = useState({
    id: 0,
    name: '',
    description: '',
    price: '',
  });
  const [menu, setMenu] = useState(menuItems);

  const handleAddMenuItem = () => {
    setMenu([...menu, newMenuItem]);
    setNewMenuItem({id: menu.length + 1 , name: '', description: '', price: '' });
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setNewMenuItem({ ...newMenuItem, [name]: value });
  };

  return (
    <>
    <Head>
        <title>User</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar username={"geto"} loginStatus={false}/>;

    <div className=" mx-auto px-4 sm:px-6 lg:px-8  mt-16">
      <h1 className="text-3xl font-bold mb-8">Menu</h1>

      <div className="flex flex-wrap mb-8">
        <input
          className="w-full sm:w-auto mb-2 sm:mb-0 mr-0 sm:mr-2 p-2 border rounded"
          type="text"
          name="name"
          value={newMenuItem.name}
          onChange={handleChange}
          placeholder="Name"
        />
        <input
          className="w-full sm:w-auto mb-2 sm:mb-0 mr-0 sm:mr-2 p-2 border rounded"
          type="text"
          name="description"
          value={newMenuItem.description}
          onChange={handleChange}
          placeholder="Description"
        />
        <input
          className="w-full sm:w-auto mb-2 sm:mb-0 mr-0 sm:mr-2 p-2 border rounded"
          type="text"
          name="price"
          value={newMenuItem.price}
          onChange={handleChange}
          placeholder="Price"
        />
        <button className="bg-blue-500 text-white p-2 rounded" onClick={handleAddMenuItem}>
          Add Item
        </button>
      </div>

      <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {menu.map((menuItem) => (
          <li key={menuItem.id} className="p-4 border rounded">
            <h2 className="text-xl font-bold mb-2">{menuItem.name}</h2>
            <p className="mb-2">{menuItem.description}</p>
            <p className="font-bold">{menuItem.price}</p>
          </li>
        ))}
      </ul>
    </div>

    <Footer />
    </>
  );
}

export default Menu;