import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { api } from "../utils/api";

const Signup: NextPage = () => {
  const router = useRouter();
  const [checkedMale, setCheckedMale] = useState<boolean>(false);
  const [checkedFemale, setCheckedFemale] = useState<boolean>(false);
  const [input, setInput] = useState({
    email: "",
    firstName: "",
    lastName: "",
    phoneNumber: "",
    password: "",
  });

  const { mutate: login } = api.users.login.useMutation({
    onSuccess: (data) => {
      router.push({
        pathname: "/",
        query: {
          token: data.jwt,
          username: data.user.firstName,
          email: data.user.email,
        },
      });
    },
  });

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    login(input);
  };

  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" dark:bg-claret  md:h-screen">
        <div className="relative flex min-h-screen flex-col justify-center overflow-hidden">
          <div className="m-auto w-full rounded-md bg-timberwolf p-6 shadow-md lg:max-w-xl">
            <h1 className="text-center text-3xl font-semibold text-rich-black ">
              Sign up
            </h1>
            <form className="mt-6" onSubmit={handleSubmit}>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Email
                </label>
                <input
                  type="email"
                  className="text-blue-700 focus:border-blue-400 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-rich-black focus:ring-opacity-40"
                  required
                  placeholder="john.doe@company.com"
                  onChange={(e) => {
                    setInput({ ...input, email: e.target.value });
                  }}
                />
              </div>

              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Password
                </label>
                <input
                  type="password"
                  className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  required
                  placeholder="•••••••••"
                  onChange={(e) => {
                    setInput({ ...input, password: e.target.value });
                  }}
                />
              </div>

              <div className="mt-6">
                <button
                  type="submit"
                  className="focus:bg-blue-600 w-full transform rounded-md bg-claret px-4 py-2 tracking-wide text-white transition-colors duration-200 hover:bg-prussian-blue focus:outline-none"
                >
                  Login
                </button>
              </div>
            </form>

            <p className="text-gray-700 mt-8 text-center text-xs font-light">
              {" "}
              Dont have an account?{" "}
              <a href="#" className="font-medium text-gamboge hover:underline">
                Sign up
              </a>
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Signup;
