import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const Salon: NextPage = () => {

  //const searchNames: string[] = ["Banja Luka", "Sarajevo", "Tuzla", "Mostar", "Zenica", "Bihać", "Trebinje", "Goražde", "Široki Brijeg", "Visoko", "Gradačac", "Prijedor", "Doboj", "Bijeljina", "Bugojno", "Velika Kladuša", "Travnik", "Kakanj", "Konjic", "Čapljina", "Živinice", "Livno", "Srebrenica", "Brčko", "Bosanska Krupa", "Bosanski Petrovac", "Bosanska Dubica", "Bosanski Novi"]

  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username={"geto"}/>;
      
      <div className="flex-grow sm:mt-6">
        <div className="mx-auto max-w-7xl py-12 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">
            Postavke salona
          </h1>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-white shadow shadow-gray-700 rounded-lg px-6 py-8">
              <h2 className="text-xl font-bold text-gray-900 mb-4">
                Lične informacije
              </h2>

              <form>
              <div className="flex justify-center mb-4">
                <div className="w-full h-60 overflow-hidden">
                  <img
                    src="https://via.placeholder.com/1336x768"
                    alt="Profile picture"
                    className="object-cover w-full h-full"
                  />
                </div>
              </div>
              <div className="flex justify-center mb-4">
                <button
                  type="button"
                  className="text-blue-500 font-medium"
                >
                  Promijeni sliku
                </button>
              </div>
                <div className="mb-4">
                  <label
                    htmlFor="name"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Naziv frizerskog salona
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    placeholder="Geto"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <div className="mb-4 flex gap-4">
                  <div className="w-full">
                    <label
                          htmlFor="city"
                          className="block text-gray-700 font-bold mb-2"
                    >
                        Grad
                    </label>
                    <input
                        type="text"
                          id="city"
                          name="city"
                          placeholder="Zenica"
                          className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    />
                  </div>
                  <div className="w-full">
                    <label
                        htmlFor="address"
                        className="block text-gray-700 font-bold mb-2"
                    >
                        Adresa
                    </label>
                    <input
                        type="text"
                        id="address"
                        name="address"
                        placeholder="Bulevar kralja Tvrtka 1"
                        className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    />
                  </div>
                </div>
                
                <div className="mb-4">
                  <label
                    htmlFor="email"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    placeholder="geto@gmail.com"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <div className="mb-4">
                  <label
                    htmlFor="phone"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Broj telefona
                  </label>
                  <input
                    type="text"
                    id="phone"
                    name="phone"
                    placeholder="+387 61 123 456"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <div>
                  <label
                    htmlFor="description"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Opis
                  </label>
                  <textarea name="description" id="description" className="w-full h-28 border border-gray-300 px-1"></textarea>
                </div>
                <div className="mb-4">
                  <label
                    htmlFor="password"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Trenutna šifra
                  </label>
                  <input
                    type="password"
                    id="password"
                    name="password"
                    placeholder="********"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <button
                  type="submit"
                  className="bg-blue-500 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline hover:bg-blue-600"
                >
                  Sačuvaj
                </button>
              </form>
            </div>

            <div className="bg-white shadow shadow-gray-700 rounded-lg px-6 py-8 h-fit">
              <h2 className="text-xl font-bold text-gray-900 mb-4">
                Sigurnosne postavke
              </h2>
              <h3 className="text-l font-normal text-gray-900 mb-4">
                Promijeni šifru
              </h3>
              <form>
                <div className="mb-4">
                  <label
                    htmlFor="password"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Nova šifra
                  </label>
                  <input
                    type="password"
                    id="password"
                    name="password"
                    placeholder="********"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>

                <div className="mb-4">
                  <label
                    htmlFor="confirm-password"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Potvrdi šifru
                  </label>
                  <input
                    type="password"
                    id="confirm-password"
                    name="confirm-password"
                    placeholder="********"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <div className="mb-4">
                  <label
                    htmlFor="password"
                    className="block text-gray-700 font-bold mb-2"
                  >
                    Trenutna šifra
                  </label>
                  <input
                    type="password"
                    id="password"
                    name="password"
                    placeholder="********"
                    className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
                <div className="mb-4">
                  <h4 className="text-l font-bold text-gray-900 mb-4">Vaša šifra mora da sadrži:</h4>
                  <ul className="list-disc ml-4 mb-8">
                    <li>Najmanje 8 znakova</li>
                    <li>Najmanje 1 broj</li>
                    <li>Najmanje 1 veliko slovo</li>
                  </ul>

                </div>
                <button
              type="submit"
              className="bg-blue-500 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline hover:bg-blue-600"
            >
              Sačuvaj
                </button>
              </form>
            </div>
            
          </div>
        </div>
      </div>

      <Footer />

    </>
  );
};

export default Salon;