import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "../utils/api";

const Signup: NextPage = () => {
  const [checkedMale, setCheckedMale] = useState<boolean>(false);
  const [checkedFemale, setCheckedFemale] = useState<boolean>(false);
  const [input, setInput] = useState({
    email: "",
    firstName: "",
    lastName: "",
    phoneNumber: "",
    password: "",
  });

  const { mutate: signup } = api.users.signup.useMutation();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const { email, firstName, lastName, phoneNumber, password } = input;
    signup({
      email: email,
      firstname: firstName,
      lastname: lastName,
      password: password,
      phoneNumber: phoneNumber,
      gender: checkedMale ? "Male" : "Female",
    });
  };

  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" dark:bg-claret  md:h-screen">
        <div className="relative flex min-h-screen flex-col justify-center overflow-hidden">
          <div className="m-auto w-full rounded-md bg-timberwolf p-6 shadow-md lg:max-w-xl">
            <h1 className="text-center text-3xl font-semibold text-rich-black ">
              Sign up
            </h1>
            <form className="mt-6" onSubmit={handleSubmit}>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Email
                </label>
                <input
                  type="email"
                  className="text-blue-700 focus:border-blue-400 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-rich-black focus:ring-opacity-40"
                  required
                  placeholder="john.doe@company.com"
                  onChange={(e) => {
                    setInput({ ...input, email: e.target.value });
                  }}
                />
              </div>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  First Name
                </label>
                <input
                  className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  required
                  placeholder="John"
                  onChange={(e) => {
                    setInput({ ...input, firstName: e.target.value });
                  }}
                />
              </div>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Last Name
                </label>
                <input
                  className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  required
                  placeholder="Doe"
                  onChange={(e) => {
                    setInput({ ...input, lastName: e.target.value });
                  }}
                />
              </div>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Phone Number
                </label>
                <input
                  type="tel"
                  className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  required
                  placeholder="123-456-7890"
                  onChange={(e) => {
                    setInput({ ...input, phoneNumber: e.target.value });
                  }}
                />
              </div>
              <div className="mb-2">
                <label className="text-gray-800 block text-sm font-semibold">
                  Password
                </label>
                <input
                  type="password"
                  className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block w-full rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  required
                  placeholder="•••••••••"
                  onChange={(e) => {
                    setInput({ ...input, password: e.target.value });
                  }}
                />
              </div>
              <div className="mb-2 ">
                <label className="text-gray-800 block text-sm font-semibold">
                  Sex
                </label>
                <div className="flex items-center justify-center gap-4">
                  <label>Male</label>
                  <input
                    type="checkbox"
                    onChange={() => {
                      setCheckedMale(!checkedMale);
                    }}
                    className="text-blue-700 focus:border-blue-400 focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  />

                  <label>Female</label>
                  <input
                    onChange={() => {
                      setCheckedFemale(!checkedFemale);
                    }}
                    type="checkbox"
                    className="text-blue-700 focus:border-blue-400
                   focus:ring-blue-300 dark:placeholder-gray-400 mt-2 block rounded-md border bg-white px-4 py-2 focus:outline-none focus:ring focus:ring-opacity-40"
                  />
                </div>
              </div>
              <a href="#" className="text-blue-600 text-xs hover:underline">
                Forget Password?
              </a>
              <div className="mt-6">
                <button className="focus:bg-blue-600 w-full transform rounded-md bg-claret px-4 py-2 tracking-wide text-white transition-colors duration-200 hover:bg-prussian-blue focus:outline-none">
                  Login
                </button>
              </div>
            </form>

            <p className="text-gray-700 mt-8 text-center text-xs font-light">
              {" "}
              Already have an account?{" "}
              <a href="#" className="font-medium text-gamboge hover:underline">
                Login
              </a>
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Signup;
